[package]
edition = "2021"
name = "pixie-core"
version = "0.1.0"

[dependencies]
actix-files = "0.6.0"
actix-web = "4.0.1"
anyhow = "1.0.57"
clap = { version = "3.1.15", features = ["derive"] }
env_logger = "0.9.0"
interfaces = "0.0.8"
ipnet = "2.5.0"
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"

[features]
