dnsmasq:
  networks:
    - interface: wlan0
      proxy: 192.168.1.100
http:
  listen_on: 0.0.0.0:8080
  max_payload: 10000000
udp:
  listen_on: 0.0.0.0:25640
  chunk_broadcast: 192.168.1.255:4041
  hint_broadcast: 192.168.1.255:4042
  bits_per_second: 52428800
groups:
  asdf: 0
  qwer: 1
boot:
  unregistered: register
  default: wait
images:
  - contestant
  - worker
