[package]
edition = "2021"
name = "pixie-push"
version = "0.1.0"
[dependencies]
anyhow = "1.0.58"
blake3 = "1.3.1"
serde_json = "*"

[dependencies.clap]
features = ["derive"]
version = "3.2.8"

[dependencies.pixie-core]
path = "../pixie-core"
version = "0.1.0"
