[package]
edition = "2021"
name = "pixie-server"
version = "0.1.0"

[dependencies]
actix-files = "0.6.2"
actix-rt = "2.9.0"
actix-web = "4.4.0"
actix-web-httpauth = "0.8.1"
anyhow = "1.0.75"
blake3 = "1"
clap = { version = "4.4.11", features = ["derive"] }
env_logger = "0.10.1"
interfaces = "0.0.9"
ipnet = { version = "2.9.0", features = ["serde"] }
libc = "0.2.150"
log = "0.4.20"
macaddr = { version = "1.0.1", features = ["serde"] }
mktemp = "0.5.1"
postcard = { version = "1.0.8", default-features = false, features = ["alloc"] }
serde = "1.0.193"
serde_derive = "1.0.193"
serde_yaml = "0.9"
tokio = { version = "1.34.0", features = ["macros", "fs"] }
serde_json = "1.0.108"
hostfile = "0.2.0"
hex = "0.4.3"

[dependencies.pixie-shared]
path = "../pixie-shared"
features = ["std"]
