hosts:
  listen_on: 10.0.0.1
  #static_dhcp: [10.187.100.1, 10.187.200.200]
  hostsfile: /etc/hosts
  broadcast_speed: 52428800
http:
  listen_on: 0.0.0.0:8080
  password: secret
groups:
  - [room0, 0]
  - [room1, 1]
images:
  - contestant
  - worker
