[package]
name = "pixie-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-timers = { version = "0.2.5", features = ["futures"] }
itertools = "0.10.5"
macaddr = "1.0.1"
pixie-shared = { version = "0.1.0", path = "../pixie-shared", features = ["macaddr", "std"] }
reqwasm = "0.5.0"
serde = "1.0.151"
sycamore = { version = "0.8.2", features = ["sycamore-futures", "futures", "suspense"] }
web-sys = "0.3.60"
