[package]
name = "pixie-web"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.29"
gloo-timers = { version = "0.2.6", features = ["futures"] }
macaddr = "1.0.1"
pixie-shared = { version = "0.1.0", path = "../pixie-shared", features = ["macaddr", "std"] }
reqwasm = "0.5.0"
serde = "1.0.193"
serde_json = "1.0.108"
sycamore = { version = "0.8.2", features = ["sycamore-futures", "futures", "suspense"] }
wasm-bindgen = "0.2.89"
web-sys = { version = "0.3.66", features = ["Location"] }
